# This is a basic workflow to help you get started with Actions

name: 🚀 Deploy Application

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches:
      ["main"]
      # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web-deploy"
  web-deploy:
    name:
      🎉 Deploy Application on every commit into main
      # The type of runner that the job will run on
    runs-on:
      ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 🚚 Get latest code
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses:
          actions/checkout@v3

          # Install new dependencies and move assets
      - name: 🛠️ Reinstall composer and move assets
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/html
            git pull
            
            

            
            
